### ISSUE TITLE
觀影心得回饋

### ISSUE THREAD

**Issue by azole** [tyzx5246/hello-git#2]
謝謝你的筆記，每個人都有自己合適的方式跟節奏，希望這部影片可以幫助你找到適合自己的學習方式。另外，你筆記中有提到，自己在上課時的吸收速度比較慢，雖然我比較鼓勵盡量在上課時把不懂的問到懂，但的確每個人的方式都不同，你在課後複習的時候，如果有遇到問題，隨時可以在 slack 傳訊息給我討論，我能回覆的時候就會回覆，要善用各種資源幫助自己學習，包括查詢各種資料、包括你的老師與同學們，最重要的是，你學會了，這樣就好了，好嗎？

**Comment by tyzx5246** [comment]
> 謝謝你的筆記，每個人都有自己合適的方式跟節奏，希望這部影片可以幫助你找到適合自己的學習方式。另外，你筆記中有提到，自己在上課時的吸收速度比較慢，雖然我比較鼓勵盡量在上課時把不懂的問到懂，但的確每個人的方式都不同，你在課後複習的時候，如果有遇到問題，隨時可以在 slack 傳訊息給我討論，我能回覆的時候就會回覆，要善用各種資源幫助自己學習，包括查詢各種資料、包括你的老師與同學們，最重要的是，你學會了，這樣就好了，好嗎？

**Comment by tyzx5246** [comment]
> 謝謝你的筆記，每個人都有自己合適的方式跟節奏，希望這部影片可以幫助你找到適合自己的學習方式。另外，你筆記中有提到，自己在上課時的吸收速度比較慢，雖然我比較鼓勵盡量在上課時把不懂的問到懂，但的確每個人的方式都不同，你在課後複習的時候，如果有遇到問題，隨時可以在 slack 傳訊息給我討論，我能回覆的時候就會回覆，要善用各種資源幫助自己學習，包括查詢各種資料、包括你的老師與同學們，最重要的是，你學會了，這樣就好了，好嗎？

**Comment by detectviz** [comment]
> 謝謝你的筆記，每個人都有自己合適的方式跟節奏，希望這部影片可以幫助你找到適合自己的學習方式。另外，你筆記中有提到，自己在上課時的吸收速度比較慢，雖然我比較鼓勵盡量在上課時把不懂的問到懂，但的確每個人的方式都不同，你在課後複習的時候，如果有遇到問題，隨時可以在 slack 傳訊息給我討論，我能回覆的時候就會回覆，要善用各種資源幫助自己學習，包括查詢各種資料、包括你的老師與同學們，最重要的是，你學會了，這樣就好了，好嗎？

好的，謝謝老師的建議！
